### ISSUE TITLE
Race condition in HlsDownloader leading to ConcurrentModificationException

### ISSUE THREAD

**Issue by Ilya-Gh** [kaltura/playkit-dtg-android#115]
Follow up on https://github.com/kaltura/playkit-dtg-android/issues/101

The Race condition in HlsDownloader leading to ConcurrentModificationException & NPE ocurred after update from [v2.6.4 to v2.6.9](https://github.com/kaltura/playkit-dtg-android/compare/release/v2.6.4...v2.6.9).

Currently, the `HlsDownloader#createDownloadTasks` function can be called from 2 places that are run in 2 separate Threads. 
1. On track selection from `TrackSelectorImp.apply`, which uses AsyncTasks `sDefaultExecutor`. 
https://github.com/kaltura/playkit-dtg-android/blob/d92e41ed7f6d8ec572a82b5cf6cab8f6b360e971/dtglib/src/main/java/com/kaltura/dtg/TrackSelectorImp.java#L39 
2. Download services after metadata completes, which uses a `ThreadPoolExecutor` to invoke `HlsDownloader#createDownloadTasks` further down the stack via `AbrDownloader#apply` call.
https://github.com/kaltura/playkit-dtg-android/blob/d92e41ed7f6d8ec572a82b5cf6cab8f6b360e971/dtglib/src/main/java/com/kaltura/dtg/DownloadService.java#L395
https://github.com/kaltura/playkit-dtg-android/blob/d92e41ed7f6d8ec572a82b5cf6cab8f6b360e971/dtglib/src/main/java/com/kaltura/dtg/AbrDownloader.java#L93

The race condition appeared [after metadata fetching was moved ](https://github.com/kaltura/playkit-dtg-android/pull/91/files#diff-4042193978765f1c2e1fcd3f0a1d7df3fcf8190a765393531233023ce7162f3aR354.)to a dedicated `ThreadPoolExecutor` from AsyncTasks `sDefaultExecutor` which was reused reusing the same Thread for both calls. 

#### Steps to reproduce

The sample project:
https://github.com/Ilya-Gh/playkit-dtg-android/commit/e21576dc3d7ad95b09ca73f287614d2106f0364c

I have added the code that restarts the download when it finishes so it will be easier to observe the crash (the reproducibility rate is about 5% for me).

The line that makes the app crash is https://github.com/Ilya-Gh/playkit-dtg-android/commit/e21576dc3d7ad95b09ca73f287614d2106f0364c#diff-d59630304bf15fb3aa1e3709f4ca60a982485601c69b7eff2d94c94e37cad140R501 

1. Start downloading HLS video.

#### Expected Results

The download should start

#### Actual Results

The following exceptions are thrown from dtg: 

```
FATAL EXCEPTION: AsyncTask #2
Process: com.kaltura.dtg.demo, PID: 6983
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.next(ArrayList.java:860)
	at com.kaltura.dtg.hls.HlsDownloader.createDownloadTasks(HlsDownloader.java:98)
	at com.kaltura.dtg.AbrDownloader.applyInitialTrackSelection(AbrDownloader.java:122)
	at com.kaltura.dtg.hls.HlsDownloader.applyInitialTrackSelection(HlsDownloader.java:314)
	at com.kaltura.dtg.AbrDownloader.apply(AbrDownloader.java:235)
	at com.kaltura.dtg.TrackSelectorImp.lambda$apply$0$com-kaltura-dtg-TrackSelectorImp(TrackSelectorImp.java:39)
	at com.kaltura.dtg.TrackSelectorImp$$ExternalSyntheticLambda0.run(Unknown Source:4)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)
```

**Comment by kaltura-hooks** [comment]
Hi @Ilya-Gh,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa \"kaltura*\"
```	
	For deb based systems:
```	
	# dpkg -l \"kaltura-*\"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by GouravSna** [comment]
Hi @Ilya-Gh , I have reopened https://github.com/kaltura/playkit-dtg-android/issues/101, hence closing this one.
