### ISSUE TITLE
ContentManager fails to parse master playlists with a query string in URL

### ISSUE THREAD

**Issue by alex-berdnikov** [kaltura/playkit-dtg-android#78]
Whenever a url of any master HLS manifest file contains a query string, library fails to parse it. The reason appears to be a bug in the library, which causes the query string to be appended to the url one more time. So, for example, if we have a url like https://lol.srvr.8181.com/playlists/hls.m3u8?param1=hello&param2=world, at some phase of attempting the metadata url becomes
https://lol.srvr.8181.com/playlists/hls.m3u8?param1=hello&param2=world?param1=hello&param2=world which often prevents servers from handling such a request right. Therefore, the library can't obtain playlist's content and can't parse it as a result.

**Comment by kaltura-hooks** [comment]
Hi @alex-berdnikov,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa \"kaltura*\"
```	
	For deb based systems:
```	
	# dpkg -l \"kaltura-*\"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by alex-berdnikov** [comment]
Yes, the the issue is consistent. I use the library in an Android application, thus it's self-hosted.
I do believe that the bug is very simple and doesn't have anything to do with Android Studio version or other stuff. I have debugged it through and through and the issue is that there's simply no handling for a scenario when master playlist url and particular media urls both have query strings.
So, let's say, master playlist URL has ?param1=hey&param2=hi and a particular playlist url like 
hls-480p.m3u8?param1=hey&param2=hi has the same query string, the library just re-appends the query string from the master playlist url to the media content url without checking if the latter already has its own query string. As a result, media playlist url will have two query strings because query string from master url will be appended to all the media urls no matter whar. I'm sure you can reproduce it very easily without any additional information. So in this example the final result for media url would be hls-480p.m3u8?param1=hey&param2=hi?param1=hey&param2=hi (same params appear twice)

**Comment by giladna** [comment]
@alex-berdnikov 

thanks for your report.

We will take a closer look into the issue
seems there are more aspects to cover in the fix.

we have opened internal issue FEC-10137

**Comment by GouravSna** [comment]
Hi @alex-berdnikov , We have fixed it. It is there in our `current` branch for QA. 
You may wait for the next official release.

**Comment by alex-berdnikov** [comment]
Hi, thank you for a heads up!
