### ISSUE TITLE
Provide API to cancel metadata loading

### ISSUE THREAD

**Issue by Ilya-Gh** [kaltura/playkit-dtg-android#87]
### Background

Loading metadata is an initial mandatory step before the download can be started. Metadata is fetched using `DownloadItem#loadMetadata` method:

https://github.com/kaltura/playkit-dtg-android/blob/5636c98d11523ae88918bffedc59dca9bc989d15/dtglib/src/main/java/com/kaltura/dtg/DownloadItem.java#L26

However, there is no way to cancel [metadata loading](https://github.com/kaltura/playkit-dtg-android/blob/5636c98d11523ae88918bffedc59dca9bc989d15/dtglib/src/main/java/com/kaltura/dtg/DownloadService.java#L340), which includes HTTP requests:

 https://github.com/kaltura/playkit-dtg-android/blob/5636c98d11523ae88918bffedc59dca9bc989d15/dtglib/src/main/java/com/kaltura/dtg/DownloadService.java#L404

Not being able to cancel metadata results in `DownloadStateListener#onDownloadMetadata` and `DownloadStateListener#onTracksAvailable` and others callbacks invocations even after download cancellation using 
 `ContentManager#removeItem`
 https://github.com/kaltura/playkit-dtg-android/blob/7572fa6a1c12c8c67726aa674d32c507d49abba5/dtglib/src/main/java/com/kaltura/dtg/ContentManager.java#L100

### Proposal
Provide API to cancel metadata loading HTTP requests and other related work. 

Another option would be to cancel pending metadata loading in `ContentManager#removeItem` for the current item.

**Comment by kaltura-hooks** [comment]
Hi @Ilya-Gh,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa \"kaltura*\"
```	
	For deb based systems:
```	
	# dpkg -l \"kaltura-*\"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by OrenMe** [comment]
Thanks @Ilya-Gh this is a good suggestion.
We will take this internally in the team to to provide a proper solution.

**Comment by GouravSna** [comment]
[#87](https://github.com/kaltura/playkit-dtg-android/issues/87) [#FEC-10618](https://kaltura.atlassian.net/browse/FEC-10618)

**Comment by GouravSna** [comment]
Hi @Ilya-Gh , I have one question. 

> However, there is no way to cancel [metadata loading](https://github.com/kaltura/playkit-dtg-android/blob/5636c98d11523ae88918bffedc59dca9bc989d15/dtglib/src/main/java/com/kaltura/dtg/DownloadService.java#L340), which includes HTTP requests:
> 
Yes, there is no way to cancel this metadata download because it is a primary step to start a download and it is mandatory. It involves HTTP requests because we prepare an item for a download.
> 
> Not being able to cancel metadata results in `DownloadStateListener#onDownloadMetadata` and `DownloadStateListener#onTracksAvailable` and others callbacks invocations even after download cancellation using
> `ContentManager#removeItem`
> 
You can call removeItem in `DownloadStateListener#onDownloadMetadata` and `DownloadStateListener#onTracksAvailable`  and it will remove the item from DB.
BUT
What I saw that if you call contentManager.removeItem(item.getItemId()); and item.startDownload(); one after another then removeItem takes time due to DB operation that's why startDownload actually happen but does not perform anything.

Is the above case you are trying ? 
Please let me know what you are trying to achieve with this metadata cancel API so that we can build the solution accordingly. 

> 
> ### Proposal
> 
> Provide API to cancel metadata loading HTTP requests and other related work.
> 
> Another option would be to cancel pending metadata loading in `ContentManager#removeItem` for the current item.

**Comment by Ilya-Gh** [comment]
@GouravSna Thanks for taking a look at the proposal. 

> Yes, there is no way to cancel this metadata download because it is a primary step to start a download and it is mandatory. It involves HTTP requests because we prepare an item for a download.

I would expect any async job especially involving I/O operation to be cancellable as it's unknown how much time the operation would take, and considering that the download library is not tied to any Activity and has application-wide scope, it would be nice if users can safely stop the download, without wasting system resources and network traffic (if the request is not yet started). 

For example, DownloadTasks are canceled if the item is removed or paused.

https://github.com/kaltura/playkit-dtg-android/blob/5636c98d11523ae88918bffedc59dca9bc989d15/dtglib/src/main/java/com/kaltura/dtg/DownloadService.java#L198
https://github.com/kaltura/playkit-dtg-android/blob/5636c98d11523ae88918bffedc59dca9bc989d15/dtglib/src/main/java/com/kaltura/dtg/DownloadService.java#L249


> Please let me know what you are trying to achieve with this metadata cancel API so that we can build the solution accordingly.

Our downloading flow heavily relies on `DownloadStateListener#onDownloadMetadata` and `DownloadStateListener#onTracksAvailable` callbacks and it's against common sense that they are invoked after the download was removed, which leads to unwanted side-effects, such as incorrect downloads status. 

Thanks for the cooperation.

**Comment by GouravSna** [comment]
Thanks @Ilya-Gh for the explanation. We will take it up internally.

**Comment by GouravSna** [comment]
Pull request #91 has been merged. You can test our 'current' branch before the upcoming release.
